CREATE TABLE public_feedback (
	id UUID,
	app VARCHAR(255) NOT NULL,
	user_id VARCHAR(255) NOT NULL,
	ips VARCHAR(255)[] NOT NULL,
	content VARCHAR(255) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	PRIMARY KEY (id)
);
